<?php
/**
 * Created by PhpStorm.
 * UserView: Rohrb
 * Date: 06/05/2019
 * Time: 10:09
 */

class MyAccountManager extends Model{

    /**
     * Vérifie si un titre identique existe déjà
     * @param $id    Titre du code ADE
     * @return bool     Renvoie vrai s'il y a un doublon
     */
    protected function checkIfDoubleUserID($id){
        $var = 0;
        $req = $this->getDb()->prepare('SELECT * FROM code_delete_account WHERE ID_user =:ID_user');
        $req->bindValue(':ID_user', $id);
        $req->execute();
        while ($data = $req->fetch(PDO::FETCH_ASSOC)){
            $var = $var + 1;
        }
        if ($var > 0)
            return true;
        else
            return false;

        $req->closeCursor();
    }

    public function createRandomCode($userID){
        if(! ($this->checkIfDoubleUserID($userID))){
            $req = $this->getDb()->prepare('INSERT INTO code_delete_account (ID_user, Code) 
                                         VALUES (:ID_user, :code)');

           $code = wp_generate_password();

            $req->bindParam(':ID_user', $userID);
            $req->bindParam(':code', $code);

            $req->execute();

            return $code;
        }
        else{
            $code = $this->modifyCode($userID);
            return $code;
        }
    }

    public function getAll($table)
    {
        return parent::getAll($table); // TODO: Change the autogenerated stub
    }

    public function modifyCode($id_user){
        $req = $this->getDb()->prepare('UPDATE code_delete_account SET Code=:code WHERE ID_user=:id_user');
        $code = wp_generate_password();
        $req->bindParam(':id_user', $id_user);
        $req->bindParam(':code', $code);
        $req->execute();
        return $code;
    }

    public function getCode($userID){
        $var = [];
        $req = $this->getDb()->prepare('SELECT * FROM code_delete_account WHERE ID_user = :UserID');
        $req->bindParam(':UserID', $userID);
        $req->execute();
        while ($data = $req->fetch(PDO::FETCH_ASSOC)) {
            $var[] = $data;
        }
        return $var;
        $req->closeCursor();
    }

    public function deleteCode($UserID){
        $req = $this->getDb()->prepare('DELETE FROM code_delete_account WHERE ID_user = :userID');
        $req->bindValue(':userID', $UserID);

        $req->execute();
    }

    public function modifyMyCodes($id, $login, $codes) {
        $this->modifyUser($id, $login, $codes);
    }
}